version: "3"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app
  rabbirmq:
    image: rabbitmq:3.8-management
    ports:
      - "15672:15672"