version: "3"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret-root-password
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=app
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
    volumes:
    - ./rabbitmq_definitions.json:/opt/definitions.json:ro
    - ./rabbitmq_advanced.config:/etc/rabbitmq/advanced.config:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mysql"
    command: dockerize -wait tcp://mysql:3306 -timeout 60s python run.py startapi
  ingest:
    build: .
    depends_on:
      - "mysql"
      - "rabbitmq"
    command: dockerize -wait tcp://mysql:3306 -wait tcp://rabbitmq:5672 -timeout 60s python run.py startingestor
  generator:
    build: .
    depends_on:
      - "rabbitmq"
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 60s python run.py startgenerator --delay 10
